[build]
builder = "dockerfile"
dockerfilePath = "KuizServer/Dockerfile"

[deploy]
startCommand = "dotnet KuizServer.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
