[build]
builder = "NIXPACKS"
buildCommand = "cd KuizServer && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd KuizServer/out && dotnet KuizServer.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[env]]
name = "ASPNETCORE_ENVIRONMENT"
value = "Production"

[[env]]
name = "ASPNETCORE_URLS"
value = "http://0.0.0.0:$PORT"
